### ISSUE TITLE
Two Phase Dialog does not show

### ISSUE THREAD

**Issue by MinceMan** [mariosangiorgio/RateMyApp#19]
I add to build.gradle `compile 'com.mariosangiorgio:RateMyApp:1.1'`

I'm able to build it just fine. The problem is that when I want to add an email

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity);
    getRater().appLaunched();
}

private RateMyApp getRater() {
    return new RateMyAppBuilder()
            .setEmailAddress("test@test.com")
            .build(this);
}
```

The first dialog shows as expected but when they hit "Yes" nothing happens.

**Comment by mariosangiorgio** [comment]
I'll have a look at this. Thanks for reporting the issue
